name: push-actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - '1.14'
          - '1.15'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: build 
        run: go build
