name: Publish Release
on:
  release:
    types: [created]
  create:
    ref_type: tag
jobs:
  push_to_registry:
    name: Build and push image to github packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
          registry: ghcr.io
          repository: open-strateos/sensorpush_exporter
          tag_with_ref: true
  publish_binaries:
    name: Build binaries and attach them to the release
    runs-on: ubuntu-20.04
    if: github.event.release
    strategy:
      matrix:
        goos:
          - linux
          - darwin
          - windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.13
          goarch: amd64
          goos: ${{ matrix.goos }}
          binary_name: sensorpush_exporter
        