name: Publish Release Binaries
on:
  release:
    types: [created]
jobs:
  publish_binaries:
    name: Build binaries and attach them to the release
    runs-on: ubuntu-20.04
    if: github.event.release
    strategy:
      matrix:
        goos:
          - linux
          - darwin
          - windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.13
          goarch: amd64
          goos: ${{ matrix.goos }}
          binary_name: sensorpush_exporter
        